""" hello_gemini.py: Hello Google Gemini
This module introduces Google Gemini API and tests whether everything is 
setup correctly to use the Google Gemini LLM

@author: Manish Bhobe
My experiments with Python, Data Science, Deep Learning & Generative AI.
Code is made available as-is & for learning purposes only, please use at your own risk!!
"""

import os
import re
from dotenv import load_dotenv, find_dotenv

import google.generativeai as genai

# load env variables from .env file
_ = load_dotenv(find_dotenv())  # read local .env file
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])


def remove_markdown(text: str) -> str:
    """
    Removes basic Markdown formatting from the given text.
    (Code generated by Google Gemini)

    Args:
        text (str): The input text with potential Markdown formatting.

    Returns:
        str: The text with Markdown formatting removed.
    """

    markdown_patterns = [
        (r"\*", r""),  # Remove single asterisks
        (r"\*\*", r""),  # Remove double asterisks
        (r"\_", r"_"),  # Convert single underscores to literal underscores
        (r"\__", r"_"),  # Convert double underscores to literal underscores
        (r"\`", r"`"),  # Convert backticks to literal backticks
        (r"#+", r""),  # Remove headings
        (r"> ", r""),  # Remove blockquotes
        (r"- ", r""),  # Remove list items
    ]

    for pattern, replacement in markdown_patterns:
        text = re.sub(pattern, replacement, text)

    return text


# create an instance of Gemini LLM
# alternatively, use "gemini-pro" instead of "gemini-1.5-flash"
model = genai.GenerativeModel("gemini-1.5-flash")
response = model.generate_content("What is Google Gemini?")
print(remove_markdown(response.text))
